### ISSUE TITLE
Variable declaration and initialization can be done within for loop declaration

### ISSUE THREAD

**Issue by nishant-jain-94** [sro-boeing-wave-2/reverse-string-js-problem-vermarahul18#1]
https://github.com/sro-boeing-wave-2/reverse-string-js-problem-vermarahul18/blob/d63048610bfc87b54541725e6e6db0f1fc70ad2c/reverse-using-iterators.js#L3-L6

**Comment by vermarahul18** [comment]
Variables declared  and initialized inside for loop.
