### ISSUE TITLE
Use es6 Arrow functions without using return keyword

### ISSUE THREAD

**Issue by nishant-jain-94** [sro-boeing-wave-2/reverse-string-js-problem-vermarahul18#2]
https://github.com/sro-boeing-wave-2/reverse-string-js-problem-vermarahul18/blob/d63048610bfc87b54541725e6e6db0f1fc70ad2c/reverse-using-built-in-function.js#L3-L6

**Comment by vermarahul18** [comment]
removed the return statement by using es6 arrow function.
